# Use an official Tomcat image as a parent image
FROM tomcat:latest

# Copy the local index.html and styles.css to the webapps directory of Tomcat
COPY index.html /usr/local/tomcat/webapps/ROOT/index.html
COPY styles.css /usr/local/tomcat/webapps/ROOT/styles.css
