version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8080"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    build:
      context: ./database
    ports:
      - "3306:3306"
